apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: nsm-monitoring
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
    extensions:
    exporters:
      jaeger:
        endpoint: "jaeger.nsm-monitoring.svc:14250"
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [jaeger]