apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: nsm-monitoring
  labels:
    app.kubernetes.io/name: otel-collector
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otel-collector
        injector.nsm.nginx.com/auto-inject: disabled
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector:latest
        command:
          - /otelcol
          - --config=/conf/otel-collector-config.yaml
        ports:
        - containerPort: 4317
        volumeMounts:
        - name: otel-collector-config
          mountPath: /conf
      volumes:
      - name: otel-collector-config
        configMap:
          name: otel-collector-config
          items:
          - key: otel-collector-config
            path: otel-collector-config.yaml