apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: nsm-monitoring
  labels:
    app.kubernetes.io/name: otel-collector
spec:
  selector:
    app.kubernetes.io/name: otel-collector
  ports:
  - name: otlp-grpc
    port: 4317
