apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus.nsm.nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus.nsm.nginx
subjects:
- kind: ServiceAccount
  name: prometheus.nsm.nginx
  namespace: nsm-monitoring