apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: nsm-monitoring
  labels:
    app.kubernetes.io/name: prometheus
spec:
  selector:
    app.kubernetes.io/name: prometheus
  ports:
  - port: 9090