apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: nsm-monitoring
  labels:
    app.kubernetes.io/name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jaeger
        injector.nsm.nginx.com/auto-inject: disabled
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
        - containerPort: 16686
        - containerPort: 6831
          protocol: UDP
        - containerPort: 14268
        - containerPort: 14250