apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: nsm-monitoring
  labels:
    app.kubernetes.io/name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
        injector.nsm.nginx.com/auto-inject: disabled
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-config
          mountPath: /etc/grafana/provisioning
        - name: grafana-dashboard
          mountPath: /var/lib/grafana/dashboards
        - name: grafana-home-dashboard
          mountPath: /usr/share/grafana/public/dashboards
      volumes:
      - name: grafana-config
        configMap:
          name: grafana-config
          items:
          - key: datasources.yaml
            path: datasources/datasources.yaml
          - key: dashboards.yaml
            path: dashboards/dashboards.yaml
      - name: grafana-dashboard
        configMap:
          name: grafana-config
          items:
          - key: nginx-mesh-top.json
            path: nginx-mesh-top.json
      - name: grafana-home-dashboard
        configMap:
          name: grafana-config
          items:
          - key: nginx-mesh-top.json
            path: home.json