apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: nsm-monitoring
  labels:
    app.kubernetes.io/name: grafana
spec:
  selector:
    app.kubernetes.io/name: grafana
  ports:
  - port: 3000